"""Kanonische, versionierte Excel-Datenverträge.

Die Verträge sind bewusst institutsneutral. Bankeigene Codes werden in den
Mappingtabellen auf die kanonischen Merkmale abgebildet. Jede fachliche Tabelle
erhält dieselben bitemporalen Metadaten.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Mapping

from .supporting import IRB_SUPPORT_FIELDS, SUPPORT_FIELDS

COMMON_COLUMNS = (
    "record_id",
    "business_key",
    "version_no",
    "as_of_date",
    "valid_from",
    "valid_to",
    "known_from",
    "known_to",
    "is_official",
    "record_status",
)


@dataclass(frozen=True)
class TableSpec:
    workbook: str
    sheet: str
    table_name: str
    columns: tuple[str, ...]
    primary_key: tuple[str, ...] = ("record_id",)
    required: bool = True

    @property
    def all_columns(self) -> tuple[str, ...]:
        return COMMON_COLUMNS + self.columns


def _t(workbook: str, sheet: str, name: str, *columns: str, required: bool = True) -> TableSpec:
    return TableSpec(workbook, sheet, f"tbl_in_{name}", tuple(columns), required=required)


TABLE_SPECS: Mapping[str, TableSpec] = {
    # 00 – Lauf, Recht und Parameter
    "run_config": _t(
        "RWA_IN_00_Run_Control.xlsx",
        "Run_Config",
        "run_config",
        "config_key",
        "config_value",
        "value_type",
        "description",
    ),
    "rule_set": _t(
        "RWA_IN_00_Run_Control.xlsx",
        "Rule_Sets",
        "rule_set",
        "rule_set_id",
        "jurisdiction",
        "calculation_type",
        "market_regime",
        "output_floor_factor",
        "reporting_currency",
        "description",
    ),
    "official_designation": _t(
        "RWA_IN_00_Run_Control.xlsx",
        "Official",
        "official_designation",
        "object_type",
        "designated_business_key",
        "designated_record_id",
        "designation_reason",
        "approved_by",
        "approved_at",
    ),
    "regulatory_parameter": _t(
        "RWA_IN_14_Rules_Parameters.xlsx",
        "Parameters",
        "regulatory_parameter",
        "parameter_key",
        "dimension_1",
        "dimension_2",
        "parameter_value",
        "unit",
        "rule_set_id",
        "legal_reference",
    ),
    "formula_definition": _t(
        "RWA_IN_14_Rules_Parameters.xlsx",
        "Formula_Registry",
        "formula_definition",
        "formula_id",
        "formula_version",
        "component",
        "expression_language",
        "legal_reference",
        "description",
    ),
    "legal_source": _t(
        "RWA_IN_14_Rules_Parameters.xlsx",
        "Legal_Sources",
        "legal_source",
        "source_id",
        "celex_eba_bafin_id",
        "title",
        "source_type",
        "jurisdiction",
        "publication_date",
        "application_date",
        "official_url",
        "local_file",
        "sha256",
    ),
    "legal_provision": _t(
        "RWA_IN_14_Rules_Parameters.xlsx",
        "Legal_Provisions",
        "legal_provision",
        "provision_id",
        "source_id",
        "article",
        "paragraph",
        "point",
        "subject",
        "decision_rule",
    ),
    # 01 – Unternehmen und Scopes
    "legal_entity": _t(
        "RWA_IN_01_Entities_Scopes.xlsx",
        "Legal_Entities",
        "legal_entity",
        "legal_entity_id",
        "lei",
        "entity_name",
        "country",
        "entity_type",
        "accounting_standard",
        "reporting_currency",
        "si_lsi_status",
        "gsii_osii_status",
    ),
    "consolidation_scope": _t(
        "RWA_IN_01_Entities_Scopes.xlsx",
        "Scopes",
        "consolidation_scope",
        "consolidation_scope_id",
        "scope_name",
        "calculation_scope",
        "parent_entity_id",
    ),
    "scope_membership": _t(
        "RWA_IN_01_Entities_Scopes.xlsx",
        "Scope_Members",
        "scope_membership",
        "consolidation_scope_id",
        "legal_entity_id",
        "consolidation_method",
        "ownership_share",
        "elimination_flag",
    ),
    "approach_permission": _t(
        "RWA_IN_01_Entities_Scopes.xlsx",
        "Permissions",
        "approach_permission",
        "consolidation_scope_id",
        "portfolio_code",
        "risk_type",
        "approach",
        "permission_reference",
        "authority",
    ),
    # 02 – Parteien und Ratings
    "party": _t(
        "RWA_IN_02_Parties_Ratings.xlsx",
        "Parties",
        "party",
        "party_id",
        "party_name",
        "country",
        "sector",
        "counterparty_type",
        "annual_sales_eur",
        "total_assets_eur",
        "sme_flag",
    ),
    "connected_client_group": _t(
        "RWA_IN_02_Parties_Ratings.xlsx",
        "Connected_Groups",
        "connected_client_group",
        "group_id",
        "group_name",
        "group_reason",
    ),
    "group_membership": _t(
        "RWA_IN_02_Parties_Ratings.xlsx",
        "Group_Members",
        "group_membership",
        "group_id",
        "party_id",
        "control_flag",
        "economic_dependency_flag",
    ),
    "external_assessment": _t(
        "RWA_IN_02_Parties_Ratings.xlsx",
        "External_Ratings",
        "external_assessment",
        "party_id",
        "ecai",
        "rating",
        "credit_quality_step",
        "rating_scope",
        "nominated_flag",
    ),
    "rating_assignment": _t(
        "RWA_IN_02_Parties_Ratings.xlsx",
        "IRB_Ratings",
        "rating_assignment",
        "party_id",
        "rating_system",
        "grade_pool",
        "pd_estimate",
        "default_flag",
        "override_flag",
        "model_version_id",
        "permission_id",
    ),
    # 03 – Accounting
    "accounting_measure": _t(
        "RWA_IN_03_Accounting.xlsx",
        "Accounting",
        "accounting_measure",
        "legal_entity_id",
        "financial_year",
        "account_code",
        "measure_type",
        "amount",
        "currency",
        "ifrs_hgb_category",
        "finrep_mapping",
        "consolidation_elimination",
    ),
    # 04 – Kreditrisiko
    "product_contract": _t(
        "RWA_IN_04_Credit_Exposures.xlsx",
        "Contracts",
        "product_contract",
        "contract_id",
        "legal_entity_id",
        "party_id",
        "product_code",
        "portfolio_code",
        "currency",
        "start_date",
        "maturity_date",
        "accounting_book",
        "regulatory_book",
        "fixed_floating",
        "reference_rate",
        "contract_rate",
        "rate_floor",
        "rate_cap",
    ),
    "facility": _t(
        "RWA_IN_04_Credit_Exposures.xlsx",
        "Facilities",
        "facility",
        "facility_id",
        "contract_id",
        "limit_amount",
        "drawn_amount",
        "committed_undrawn",
        "annex_i_class",
        "contractual_availability_limit",
        "unconditionally_cancellable_flag",
    ),
    "exposure_lot": _t(
        "RWA_IN_04_Credit_Exposures.xlsx",
        "Exposure_Lots",
        "exposure_lot",
        "exposure_id",
        "contract_id",
        "facility_id",
        "legal_entity_id",
        "party_id",
        "portfolio_code",
        "approach",
        "currency",
        "gross_carrying_amount",
        "net_carrying_amount_article_111",
        "ead_data_path",
        "nominal_amount",
        "specific_credit_adjustments",
        "general_credit_adjustments",
        "additional_valuation_adjustments",
        "other_own_funds_reductions",
        "partial_write_offs",
        "on_balance_flag",
        "committed_undrawn",
        "annex_i_class",
        "residual_maturity_years",
        "seniority",
        "default_flag",
        "npe_flag",
        "npe_classification_date",
    ),
    "sa_classification": _t(
        "RWA_IN_04_Credit_Exposures.xlsx",
        "SA_Classification",
        "sa_classification",
        "exposure_id",
        "exposure_class",
        "subclass",
        "credit_quality_step",
        "short_term_flag",
        "retail_eligible_flag",
        "transactor_flag",
        "specialised_lending_type",
        "risk_weight_override",
        "currency_mismatch_flag",
        "supporting_factor_type",
        "supporting_factor",
    ),
    "real_estate_exposure": _t(
        "RWA_IN_04_Credit_Exposures.xlsx",
        "Real_Estate",
        "real_estate_exposure",
        "exposure_id",
        "property_id",
        "property_type",
        "ipre_flag",
        "adc_flag",
        "completed_flag",
        "prudent_property_value",
        "senior_liens",
        "equal_higher_third_party_liens",
        "etv",
        "currency_mismatch_flag",
        "primary_residence_flag",
    ),
    "irb_parameter": _t(
        "RWA_IN_04_Credit_Exposures.xlsx",
        "IRB_Parameters",
        "irb_parameter",
        "exposure_id",
        "irb_subclass",
        "irb_approach",
        "pd_estimate",
        "lgd_estimate",
        "ead_estimate",
        "maturity_years",
        "annual_sales_eur",
        "financial_multiplier_flag",
        "elbe",
        "pd_floor",
        "lgd_floor",
        "ead_floor",
        "slotting_category",
    ),
    "crypto_exposure": _t(
        "RWA_IN_04_Credit_Exposures.xlsx",
        "Crypto",
        "crypto_exposure",
        "exposure_id",
        "crypto_class",
        "mica_status",
        "market_value",
        "tier1_limit_relevant_flag",
    ),
    # 05 – CRM
    "collateral_asset": _t(
        "RWA_IN_05_Collateral_CRM.xlsx",
        "Collateral",
        "collateral_asset",
        "collateral_id",
        "collateral_type",
        "owner_party_id",
        "currency",
        "market_value",
        "valuation_date",
        "haircut",
        "eligibility_flag",
        "property_id",
    ),
    "property_valuation": _t(
        "RWA_IN_05_Collateral_CRM.xlsx",
        "Property_Values",
        "property_valuation",
        "property_id",
        "market_value",
        "prudent_value",
        "valuation_date",
        "valuation_method",
        "independent_flag",
    ),
    "unfunded_protection": _t(
        "RWA_IN_05_Collateral_CRM.xlsx",
        "Guarantees",
        "unfunded_protection",
        "protection_id",
        "provider_party_id",
        "protected_amount",
        "currency",
        "maturity_date",
        "guarantor_risk_weight",
        "eligibility_flag",
    ),
    "protection_allocation": _t(
        "RWA_IN_05_Collateral_CRM.xlsx",
        "Allocations",
        "protection_allocation",
        "allocation_id",
        "exposure_id",
        "protection_type",
        "protection_id",
        "allocated_value",
        "eligible_value_after_haircut",
        "maturity_mismatch_factor",
        "currency_mismatch_factor",
        "crm_approach",
        "substitution_risk_weight",
    ),
    # 06 – CCR, CVA, CCP und Settlement
    "netting_set": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "Netting_Sets",
        "netting_set",
        "netting_set_id",
        "legal_entity_id",
        "party_id",
        "margined_flag",
        "V",
        "C",
        "NICA",
        "threshold",
        "mta",
        "addon_ird",
        "addon_fx",
        "addon_credit",
        "addon_equity",
        "addon_commodity",
        "alpha",
        "risk_weight",
    ),
    "netting_agreement": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "Netting_Agreements",
        "netting_agreement",
        "agreement_id",
        "netting_set_id",
        "jurisdiction",
        "legal_opinion_date",
        "eligible_flag",
        "margin_period_of_risk_days",
    ),
    "derivative_trade": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "Derivatives",
        "derivative_trade",
        "trade_id",
        "netting_set_id",
        "product_type",
        "risk_category",
        "notional",
        "market_value",
        "supervisory_delta",
        "adjusted_notional",
        "maturity_factor",
        "supervisory_factor",
        "clearing_status",
    ),
    "sft_trade": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "SFT",
        "sft_trade",
        "trade_id",
        "netting_set_id",
        "cash_leg",
        "security_value",
        "security_haircut",
        "fx_haircut",
        "risk_weight",
    ),
    "margin_collateral": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "Margins",
        "margin_collateral",
        "margin_id",
        "netting_set_id",
        "margin_type",
        "market_value",
        "haircut",
        "segregated_flag",
    ),
    "ccp_exposure": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "CCP",
        "ccp_exposure",
        "ccp_exposure_id",
        "netting_set_id",
        "qccp_flag",
        "client_joint_default_flag",
        "trade_ead",
        "default_fund_contribution",
        "hypothetical_ccp_capital",
        "ccp_default_fund_total",
    ),
    "cva_scope_item": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "CVA",
        "cva_scope_item",
        "cva_item_id",
        "netting_set_id",
        "approach",
        "ead",
        "effective_maturity",
        "cva_risk_weight",
        "single_name_hedge",
        "single_hedge_maturity",
        "hedge_correlation",
        "index_hedge",
        "index_hedge_maturity",
        "index_hedge_risk_weight",
        "exempt_flag",
    ),
    "cva_sensitivity": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "CVA_Sensitivities",
        "cva_sensitivity",
        "sensitivity_id",
        "cva_item_id",
        "risk_class",
        "measure",
        "bucket",
        "tenor",
        "sensitivity",
        "risk_weight",
        "correlation",
    ),
    "settlement_exposure": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "Settlement",
        "settlement_exposure",
        "settlement_id",
        "positive_price_difference",
        "business_days_late",
        "free_delivery_flag",
        "delivered_leg",
        "countervalue",
        "counterparty_risk_weight",
    ),
    "large_exposure_excess": _t(
        "RWA_IN_06_CCR_CVA_CCP.xlsx",
        "Large_Exposure",
        "large_exposure_excess",
        "excess_id",
        "connected_client_group_id",
        "excess_amount",
        "capital_charge_rate",
        "permission_reference",
    ),
    # 07 – Verbriefung
    "securitisation_pool": _t(
        "RWA_IN_07_Securitisations.xlsx",
        "Pools",
        "securitisation_pool",
        "pool_id",
        "pool_ead",
        "rwea_pool_irb_ul",
        "el_pool_irb",
        "rwea_pool_sa",
        "pool_type",
        "npe_share",
        "effective_number_exposures",
        "average_lgd",
    ),
    "securitisation_transaction": _t(
        "RWA_IN_07_Securitisations.xlsx",
        "Transactions",
        "securitisation_transaction",
        "transaction_id",
        "pool_id",
        "transaction_type",
        "institution_role",
        "sts_flag",
        "srt_flag",
        "early_amortisation_flag",
        "clean_up_call_flag",
    ),
    "securitisation_tranche": _t(
        "RWA_IN_07_Securitisations.xlsx",
        "Tranches",
        "securitisation_tranche",
        "tranche_id",
        "pool_id",
        "approach",
        "ead",
        "attachment",
        "detachment",
        "p_factor",
        "tranche_maturity",
        "credit_quality_step",
        "senior_flag",
        "sts_flag",
        "resecuritisation_flag",
        "data_sufficient_flag",
        "risk_weight_override",
    ),
    # 08 – Markt
    "trading_position": _t(
        "RWA_IN_08_Market_Risk.xlsx",
        "Positions",
        "trading_position",
        "position_id",
        "legal_entity_id",
        "desk_id",
        "instrument_type",
        "risk_class",
        "market_value",
        "notional",
        "long_short",
        "issuer_id",
        "credit_quality_step",
        "residual_maturity_years",
        "legacy_specific_charge",
        "legacy_general_charge",
        "drc_jtd",
        "drc_risk_weight",
        "drc_bucket",
        "seniority_class",
        "drc_exposure_type",
        "banking_book_securitisation_rw",
        "rrao_rate",
        "rrao_exotic_flag",
        "rrao_exempt_flag",
    ),
    "market_sensitivity": _t(
        "RWA_IN_08_Market_Risk.xlsx",
        "Sensitivities",
        "market_sensitivity",
        "sensitivity_id",
        "position_id",
        "risk_class",
        "measure",
        "bucket",
        "risk_factor",
        "tenor",
        "sensitivity",
        "risk_weight",
        "curvature_up",
        "curvature_down",
        "intra_bucket_correlation",
        "inter_bucket_correlation",
    ),
    "market_risk_factor": _t(
        "RWA_IN_08_Market_Risk.xlsx",
        "Risk_Factors",
        "market_risk_factor",
        "risk_factor_id",
        "risk_class",
        "bucket",
        "tenor",
        "currency",
        "modellable_flag",
        "liquidity_horizon_days",
    ),
    "frtb_ima_input": _t(
        "RWA_IN_08_Market_Risk.xlsx",
        "IMA_Inputs",
        "frtb_ima_input",
        "desk_id",
        "es_current_full",
        "es_current_reduced",
        "es_stress_reduced",
        "nmrf_stress_loss",
        "ima_drc",
        "imcc_yesterday",
        "imcc_60d_average",
        "ses_nmrf_yesterday",
        "ses_nmrf_60d_average",
        "backtesting_multiplier",
        "nmrf_multiplier",
        "capital_addons",
        "pla_zone",
        "ima_permission_flag",
    ),
    # 09 – Operationelles Risiko
    "business_indicator_item": _t(
        "RWA_IN_09_Operational_Risk.xlsx",
        "BI_Items",
        "business_indicator_item",
        "legal_entity_id",
        "financial_year",
        "bi_item_type",
        "amount",
        "currency",
        "ma_adjustment_flag",
    ),
    "operational_loss_event": _t(
        "RWA_IN_09_Operational_Risk.xlsx",
        "Loss_Events",
        "operational_loss_event",
        "event_id",
        "event_date",
        "booking_date",
        "event_type",
        "business_line",
        "gross_loss",
        "cash_recovery",
        "insurance_recovery",
        "currency",
    ),
    # 10 – Eigenmittel
    "capital_instrument": _t(
        "RWA_IN_10_Own_Funds_Reqs.xlsx",
        "Instruments",
        "capital_instrument",
        "instrument_id",
        "issuer_entity_id",
        "capital_class",
        "carrying_amount",
        "issue_date",
        "maturity_date",
        "eligible_flag",
        "first_day_final_five_years_amount",
    ),
    "own_funds_component": _t(
        "RWA_IN_10_Own_Funds_Reqs.xlsx",
        "Own_Funds",
        "own_funds_component",
        "component_id",
        "capital_class",
        "component_type",
        "amount",
        "sign",
        "legal_reference",
    ),
    "valuation_adjustment": _t(
        "RWA_IN_10_Own_Funds_Reqs.xlsx",
        "Prudent_Valuation",
        "valuation_adjustment",
        "valuation_id",
        "position_id",
        "method",
        "ava_category",
        "fair_value",
        "cet1_impact_share",
        "category_ava",
        "unrealised_net_gain",
        "derivative_nominal",
        "instrument_type",
    ),
    "capital_requirement": _t(
        "RWA_IN_10_Own_Funds_Reqs.xlsx",
        "Requirements",
        "capital_requirement",
        "requirement_id",
        "requirement_type",
        "rate",
        "fixed_amount",
        "basis",
        "cet1_share",
        "tier1_share",
        "authority",
        "decision_reference",
    ),
    # 11 – IRRBB
    "interest_rate_term": _t(
        "RWA_IN_11_IRRBB.xlsx",
        "Rate_Terms",
        "interest_rate_term",
        "contract_id",
        "fixed_floating",
        "reference_curve",
        "customer_margin",
        "current_rate",
        "rate_floor",
        "rate_cap",
        "repricing_frequency_months",
        "next_repricing_date",
        "pass_through_beta",
    ),
    "cashflow": _t(
        "RWA_IN_11_IRRBB.xlsx",
        "Cashflows",
        "cashflow",
        "cashflow_id",
        "contract_id",
        "legal_entity_id",
        "cashflow_type",
        "payment_date",
        "repricing_date",
        "principal_amount",
        "interest_amount",
        "fee_margin_amount",
        "currency",
        "sign",
        "behavioural_flag",
    ),
    "behavioural_assumption": _t(
        "RWA_IN_11_IRRBB.xlsx",
        "Behaviour",
        "behavioural_assumption",
        "segment",
        "assumption_type",
        "time_band_years",
        "weight",
        "beta",
        "floor",
        "cap",
        "model_version_id",
    ),
    "irrbb_scenario": _t(
        "RWA_IN_11_IRRBB.xlsx",
        "Scenarios",
        "irrbb_scenario",
        "scenario_id",
        "scenario_type",
        "currency",
        "parallel_bp",
        "short_bp",
        "long_bp",
        "probability",
        "regulatory_flag",
    ),
    # 12 – ICAAP
    "risk_taxonomy": _t(
        "RWA_IN_12_ICAAP_Scenarios.xlsx",
        "Risk_Taxonomy",
        "risk_taxonomy",
        "risk_id",
        "risk_name",
        "parent_risk_id",
        "pillar1_coverage",
        "risk_owner",
    ),
    "materiality_assessment": _t(
        "RWA_IN_12_ICAAP_Scenarios.xlsx",
        "Materiality",
        "materiality_assessment",
        "risk_id",
        "material_flag",
        "assessment_score",
        "rationale",
        "treatment",
    ),
    "economic_capital_input": _t(
        "RWA_IN_12_ICAAP_Scenarios.xlsx",
        "EC_Inputs",
        "economic_capital_input",
        "risk_id",
        "expected_loss",
        "var_loss",
        "stress_loss",
        "provisions",
        "model_risk_addon",
        "non_diversifiable_addon",
    ),
    "risk_correlation": _t(
        "RWA_IN_12_ICAAP_Scenarios.xlsx",
        "Correlations",
        "risk_correlation",
        "risk_id_a",
        "risk_id_b",
        "correlation",
    ),
    "normative_projection": _t(
        "RWA_IN_12_ICAAP_Scenarios.xlsx",
        "Normative",
        "normative_projection",
        "scenario_id",
        "projection_year",
        "profit_after_tax",
        "distributions",
        "oci_change",
        "cet1_issuance",
        "cet1_redemption",
        "trea_multiplier",
        "leverage_exposure_multiplier",
    ),
    "model_registry": _t(
        "RWA_IN_12_ICAAP_Scenarios.xlsx",
        "Model_Registry",
        "model_registry",
        "model_version_id",
        "model_name",
        "model_type",
        "owner",
        "approval_status",
        "validation_date",
        "permission_reference",
        "random_seed",
    ),
    "scenario_path": _t(
        "RWA_IN_12_ICAAP_Scenarios.xlsx",
        "Scenario_Paths",
        "scenario_path",
        "scenario_id",
        "risk_factor",
        "projection_year",
        "shock_value",
        "unit",
        "probability",
    ),
    "risk_bearing_capacity": _t(
        "RWA_IN_12_ICAAP_Scenarios.xlsx",
        "Risk_Capacity",
        "risk_bearing_capacity",
        "capacity_component",
        "amount",
        "eligibility_factor",
        "haircut",
        "management_reserve",
    ),
    # 13 – Marktdaten
    "yield_curve": _t(
        "RWA_IN_13_Market_Data.xlsx",
        "Yield_Curves",
        "yield_curve",
        "curve_id",
        "currency",
        "curve_type",
        "tenor_years",
        "zero_rate",
        "day_count",
        "compounding",
    ),
    "market_observation": _t(
        "RWA_IN_13_Market_Data.xlsx",
        "Observations",
        "market_observation",
        "observation_key",
        "observation_type",
        "currency",
        "tenor",
        "value",
        "unit",
        "source",
    ),
    # 15 – Bankmappings
    "product_mapping": _t(
        "RWA_IN_15_Bank_Mappings.xlsx",
        "Product_Mapping",
        "product_mapping",
        "bank_product_code",
        "canonical_product_type",
        "default_portfolio",
        "mapping_priority",
    ),
    "account_mapping": _t(
        "RWA_IN_15_Bank_Mappings.xlsx",
        "Account_Mapping",
        "account_mapping",
        "bank_account_code",
        "canonical_measure_type",
        "finrep_mapping",
        "bi_item_type",
    ),
    "rating_mapping": _t(
        "RWA_IN_15_Bank_Mappings.xlsx",
        "Rating_Mapping",
        "rating_mapping",
        "bank_rating_scale",
        "bank_rating",
        "canonical_grade",
        "credit_quality_step",
    ),
}


WORKBOOKS = tuple(dict.fromkeys(spec.workbook for spec in TABLE_SPECS.values()))


# Additive schema: old workbooks are normalized before required-column checks.
for _name, _defaults in (("sa_classification", SUPPORT_FIELDS), ("irb_parameter", IRB_SUPPORT_FIELDS)):
    _spec = TABLE_SPECS[_name]
    TABLE_SPECS[_name] = replace(_spec, columns=_spec.columns + tuple(k for k in _defaults if k not in _spec.columns))


def specs_for_workbook(workbook: str) -> dict[str, TableSpec]:
    return {name: spec for name, spec in TABLE_SPECS.items() if spec.workbook == workbook}
